### ISSUE TITLE
Broken links in hover window due to \ being printed

### ISSUE THREAD

**Issue by rensftw** [b0o/SchemaStore.nvim#21]
## Environment
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
SchemaStore.nvim a6759df
[My LSP config with SchemaStore.nvim](https://github.com/rensftw/.dotfiles/blob/c71aafba83d44ef510b60b169165da6951ac11a7/neovim/.config/nvim/lua/lsp/setup-lsp-servers.lua#L27C1-L46C7)

## Actual behaviour
Special characters are prefixed by `\` resulting in broken URLs.
This behaviour happens both in YAML and JSON files.

YAML example:
<img width="885" alt="image" src="https://github.com/SchemaStore/schemastore/assets/22574186/c499abd0-3d5a-4596-ae91-82d9e39a5a54">

JSON example:
<img width="879" alt="image" src="https://github.com/SchemaStore/schemastore/assets/22574186/fd7d40fb-2208-48e9-be06-9e22264a9c70">

## Expected behaviour
Escaping symbols like `\` is not visible in the hover window. Links are usable.

## Schema to reproduce issue
https://github.com/SchemaStore/schemastore/blob/master/.pre-commit-config.yaml
```yaml
---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.2'
    hooks:
      - id: prettier
        types_or: [yaml, json, javascript, css, markdown]
        always_run: true
        additional_dependencies:
          - prettier@2.8.3
          - prettier-plugin-sort-json@1.0.0
```
